apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: id36zuhhl-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c89fccecc2.2y37.p3.openshiftapps.com/rhtap/rhtap-qe:c12d139f7b1a6da16667659eed117f4322617fa4@sha256:6ca247201cf17624208ddb410cd243dbf16672063f17a8bcf7e841cad5c58c50
          name: container-image
